#!/bin/bash
# Usage: ./scripts/snapshot.sh <session-folder>
# Example: ./scripts/snapshot.sh 04-anycast-gw
#
# Snapshots the currently-running lab into Docker images tagged with the
# session name. Also generates a snapshot topology file that uses these
# images, so restore is fast.
#
# Snapshots are local Docker images; they are NOT pushed to a registry.

set -euo pipefail

SESSION="${1:-}"

if [ -z "$SESSION" ]; then
  echo "Usage: $0 <session-folder>"
  echo ""
  echo "Available sessions:"
  ls labs/ 2>/dev/null | sed 's/^/  /'
  exit 1
fi

LAB_DIR="labs/${SESSION}"

if [ ! -d "$LAB_DIR" ]; then
  echo "ERROR: Session folder not found: $LAB_DIR"
  exit 1
fi

NODES=("spine1" "spine2" "leaf1" "leaf2")
TAG_PREFIX="vxlan-snapshot-${SESSION}"

# Sanity check: are the NX-OS containers running and healthy?
echo "==> Verifying lab is running and healthy..."
for node in "${NODES[@]}"; do
  container="clab-vxlan-evpn-${node}"
  status=$(docker inspect --format '{{.State.Health.Status}}' "$container" 2>/dev/null || echo "missing")
  if [ "$status" != "healthy" ]; then
    echo "ERROR: $container is not healthy (status: $status)"
    echo "Wait for the lab to fully come up before snapshotting."
    exit 1
  fi
  echo "  $container: healthy"
done

# Save running-config on each node before snapshot
# This ensures the qcow2 has the latest config persisted
echo ""
echo "==> Saving running-config on each NX-OS node (so it persists)..."
for node in "${NODES[@]}"; do
  container="clab-vxlan-evpn-${node}"
  echo "  $node: copy running-config startup-config"
  # vrnetlab images don't expose CLI directly; we exec a shell inside
  # and call the launch helper. Actually we use SSH from the host.
  sshpass -p admin ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null \
    -o LogLevel=ERROR \
    "admin@${container}" "copy running-config startup-config" 2>/dev/null || \
    echo "    (warning: could not save startup-config on $node; snapshot may not include latest changes)"
done

# Commit each container to a tagged image
echo ""
echo "==> Committing containers to images..."
for node in "${NODES[@]}"; do
  container="clab-vxlan-evpn-${node}"
  image_tag="${TAG_PREFIX}:${node}"
  echo "  $container -> $image_tag"
  docker commit "$container" "$image_tag" > /dev/null
done

# Generate snapshot topology file
SNAPSHOT_TOPO="${LAB_DIR}/topology-snapshot.clab.yml"
echo ""
echo "==> Generating snapshot topology: $SNAPSHOT_TOPO"

cat > "$SNAPSHOT_TOPO" << EOF
# Auto-generated by snapshot.sh on $(date -u +'%Y-%m-%dT%H:%M:%SZ')
# This topology uses pre-configured Docker images instead of booting fresh.
# Restore time: ~30 seconds (vs 15-20 min for clean deploy).

name: vxlan-evpn

topology:
  kinds:
    cisco_n9kv:
      # No image at kind level - each node specifies its snapshot image
    linux:
      image: alpine:latest

  nodes:
    spine1:
      kind: cisco_n9kv
      image: ${TAG_PREFIX}:spine1
    spine2:
      kind: cisco_n9kv
      image: ${TAG_PREFIX}:spine2
    leaf1:
      kind: cisco_n9kv
      image: ${TAG_PREFIX}:leaf1
    leaf2:
      kind: cisco_n9kv
      image: ${TAG_PREFIX}:leaf2
    host1:
      kind: linux
    host2:
      kind: linux

  links:
    - endpoints: ["spine1:eth1", "leaf1:eth1"]
    - endpoints: ["spine1:eth2", "leaf2:eth1"]
    - endpoints: ["spine2:eth1", "leaf1:eth2"]
    - endpoints: ["spine2:eth2", "leaf2:eth2"]
    - endpoints: ["leaf1:eth3", "host1:eth1"]
    - endpoints: ["leaf2:eth3", "host2:eth1"]
EOF

# Report disk usage
echo ""
echo "==> Snapshot complete."
echo ""
echo "Images created:"
docker images "${TAG_PREFIX}*" --format "  {{.Repository}}:{{.Tag}}  {{.Size}}"
echo ""
echo "Total snapshot disk usage:"
docker images "${TAG_PREFIX}*" --format "{{.Size}}" | \
  awk '{ size=$1; unit=substr($1,length($1)); val=substr($1,1,length($1)-2); if(unit=="B")total+=val; else if(unit=="GB")total+=val*1024; else total+=val/1024} END {printf "  %.1f GB\n", total/1024}' 2>/dev/null || echo "  (size summary unavailable)"
echo ""
echo "To restore this snapshot later:"
echo "  ./scripts/restore.sh $SESSION"
echo ""
echo "Note: snapshot images are local-only. They are NOT in the git repo"
echo "or pushed to any registry. Each user must build their own snapshots."
