#!/bin/bash
# Usage: ./scripts/snapshot.sh <session-folder>
# Example: ./scripts/snapshot.sh 04-anycast-gw
#
# Snapshots the currently-running lab into Docker images tagged with the
# session name. Also generates a snapshot topology file that uses these
# images, so restore is fast.

set -euo pipefail

SESSION="${1:-}"

if [ -z "$SESSION" ]; then
  echo "Usage: $0 <session-folder>"
  echo ""
  echo "Available sessions:"
  ls labs/ 2>/dev/null | sed 's/^/  /'
  exit 1
fi

LAB_DIR="labs/${SESSION}"

if [ ! -d "$LAB_DIR" ]; then
  echo "ERROR: Session folder not found: $LAB_DIR"
  exit 1
fi

NODES=("spine1" "spine2" "leaf1" "leaf2")
TAG_PREFIX="vxlan-snapshot-${SESSION}"

echo "==> Verifying lab is running and healthy..."
for node in "${NODES[@]}"; do
  container="clab-vxlan-evpn-${node}"
  status=$(docker inspect --format '{{.State.Health.Status}}' "$container" 2>/dev/null || echo "missing")
  if [ "$status" != "healthy" ]; then
    echo "ERROR: $container is not healthy (status: $status)"
    exit 1
  fi
  echo "  $container: healthy"
done

echo ""
echo "==> Saving running-config on each NX-OS node..."
for node in "${NODES[@]}"; do
  container="clab-vxlan-evpn-${node}"
  echo "  $node: copy running-config startup-config"
  sshpass -p admin ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null \
    -o LogLevel=ERROR \
    "admin@${container}" "copy running-config startup-config" 2>/dev/null || \
    echo "    (warning: could not save startup-config on $node)"
done

echo ""
echo "==> Committing containers to images..."
for node in "${NODES[@]}"; do
  container="clab-vxlan-evpn-${node}"
  image_tag="${TAG_PREFIX}:${node}"
  echo "  $container -> $image_tag"
  docker commit "$container" "$image_tag" > /dev/null
done

# Generate snapshot topology file
# IMPORTANT: do NOT declare empty kinds blocks — containerlab panics on them.
# Just specify the image directly on each node.
SNAPSHOT_TOPO="${LAB_DIR}/topology-snapshot.clab.yml"
echo ""
echo "==> Generating snapshot topology: $SNAPSHOT_TOPO"

cat > "$SNAPSHOT_TOPO" << EOF
# Auto-generated by snapshot.sh on $(date -u +'%Y-%m-%dT%H:%M:%SZ')
# Uses pre-configured Docker images instead of booting fresh.
# Restore time: ~30-60 seconds vs 15-20 min for clean deploy.

name: vxlan-evpn

topology:
  nodes:
    spine1:
      kind: cisco_n9kv
      image: ${TAG_PREFIX}:spine1
    spine2:
      kind: cisco_n9kv
      image: ${TAG_PREFIX}:spine2
    leaf1:
      kind: cisco_n9kv
      image: ${TAG_PREFIX}:leaf1
    leaf2:
      kind: cisco_n9kv
      image: ${TAG_PREFIX}:leaf2
    host1:
      kind: linux
      image: alpine:latest
    host2:
      kind: linux
      image: alpine:latest

  links:
    - endpoints: ["spine1:eth1", "leaf1:eth1"]
    - endpoints: ["spine1:eth2", "leaf2:eth1"]
    - endpoints: ["spine2:eth1", "leaf1:eth2"]
    - endpoints: ["spine2:eth2", "leaf2:eth2"]
    - endpoints: ["leaf1:eth3", "host1:eth1"]
    - endpoints: ["leaf2:eth3", "host2:eth1"]
EOF

echo ""
echo "==> Snapshot complete."
echo ""
echo "Images created:"
docker images "${TAG_PREFIX}*" --format "  {{.Repository}}:{{.Tag}}  {{.Size}}"
echo ""
echo "To restore later:"
echo "  ./scripts/restore.sh $SESSION"
